Account.create!([{user_id: 1, account_number: '000-------90'},
{user_id: 1, account_number: '3----------10'},
{user_id: 1, account_number: '4-------8'}])

Transaction.create!([{account_id: 1,category: 'course', comment: 'Rennes', amount: -2.17, done: true},
{account_id: 1,category: 'Transfert', comment: 'amaury', amount: 400.0, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -5.41, done: true},
{account_id: 1,category: 'Train', comment: 'Paris -> Rennes', amount: -32.0, done: true},
{account_id: 1,category: 'Santé', comment: 'Remb. SMEBA', amount: 2.24, done: true},
{account_id: 1,category: 'Livre', comment: 'la procure', amount: -13.5, done: true},
{account_id: 1,category: 'Banque', comment: 'Cotisation Csca Option 3 Avec Dnc ', amount: -4.4, done: true},
{account_id: 1,category: 'course', comment: 'Rennes', amount: -7.57, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -7.06, done: true},
{account_id: 1,category: 'Livre', comment: 'HTML et CSS', amount: -5.0, done: true},
{account_id: 1,category: 'Transfert', comment: 'from 4-----------8', amount: 350.0, done: true},
{account_id: 1,category: 'Metro', comment: 'semaine 31/07 au 6/08', amount: -22.15, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -6.11, done: true},
{account_id: 1,category: 'telphone', comment: 'facture', amount: -25.0, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -3.29, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -30.25, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -22.19, done: true},
{account_id: 1,category: 'coiffeur', comment: 'Paris', amount: -26.0, done: true},
{account_id: 1,category: 'équipement', comment: 'balance', amount: -14.99, done: true},
{account_id: 1,category: 'vetement', comment: 'pantalon', amount: -129.0, done: true},
{account_id: 1,category: 'Retrait', comment: 'Paris', amount: -20.0, done: true},
{account_id: 1,category: 'extra course', comment: 'Petit déjeuner', amount: -2.9, done: true},
{account_id: 1,category: 'informatique', comment: 'Clez USB 3.0', amount: -12.99, done: true},
{account_id: 1,category: 'Santé', comment: 'medecin', amount: -25.0, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -2.45, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -4.78, done: true},
{account_id: 1,category: 'Transfert', comment: 'from 4-------------8', amount: 350.0, done: true},
{account_id: 1,category: 'course', comment: 'Pairs', amount: -32.52, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -5.5, done: true},
{account_id: 1,category: 'Metro', comment: 'Semaine juillet', amount: -22.15, done: true},
{account_id: 1,category: 'équipement', comment: 'Vers mesureur', amount: -5.99, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -2.95, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -2.52, done: true},
{account_id: 1,category: 'Retrait', comment: 'Paris', amount: -20.0, done: true},
{account_id: 1,category: 'Train', comment: 'Paris->Rennes', amount: -37.0, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -4.45, done: true},
{account_id: 1,category: 'restaurant', comment: 'avec Yseult', amount: -23.5, done: true},
{account_id: 1,category: 'course', comment: 'Rennes', amount: -3.42, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -4.29, done: true},
{account_id: 1,category: 'Metro', comment: 'Paris', amount: -14.5, done: true},
{account_id: 1,category: 'Metro', comment: 'Paris', amount: -7.3, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -8.56, done: true},
{account_id: 1,category: 'Metro', comment: 'Paris<->Versaille', amount: -7.1, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -4.79, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -6.13, done: true},
{account_id: 1,category: 'Train', comment: 'Vannes->Rennes', amount: -15.0, done: true},
{account_id: 1,category: 'course', comment: 'Paris', amount: -29.95, done: true},
{account_id: 1,category: 'Metro', comment: 'Paris', amount: -14.5, done: true},
{account_id: 1,category: 'Essence', comment: 'Etel', amount: -20.02, done: true},
{account_id: 1,category: 'Livre', comment: 'Livre c++', amount: -29.9, done: true},
{account_id: 1,category: 'course', comment: 'carrefourmarket', amount: -20.69, done: true},
{account_id: 1,category: 'autre', comment: 'Début', amount: 286.2, done: true},
{account_id: 1,category: 'autre', comment: 'Début', amount: 1719.59, done: true},
{account_id: 1,category: 'Transfert', comment: 'to 000---------90', amount: -350.0, done: true},
{account_id: 1,category: 'Transfert', comment: 'to 000---------90', amount: -350.0, done: true},
{account_id: 1,category: 'autre', comment: 'Début', amount: 4120.37, done: true}])